### ISSUE TITLE
Upgrade to Scrapy 1.1

### ISSUE THREAD

**Issue by robsonpeixoto** [scrapinghub/scrapinghub-stack-hworker#8]

**Comment by jesuslosada** [comment]
This stack is available to provide compatibility with old projects created on Scrapy Cloud 1.0, but it will not receive updates for recent Scrapy versions. If you need a stack containing a recent Scrapy version, check this repository please: https://github.com/scrapinghub/scrapinghub-stack-scrapy
Note that there's a branch for each minor Scrapy version (1.2, 1.3, etc.) and there are also branches that provide Python 3 support too.

@vshlapakov I think this issue can be closed.

**Comment by vshlapakov** [comment]
@jesuslosada Right, you described it well. Thanks, closing.
